// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VotifyDataAccess.Database;

#nullable disable

namespace VotifySystem.Migrations
{
    [DbContext(typeof(VotifyDatabaseContext))]
    partial class VotifyDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("VotifySystem.Common.Models.Candidate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConstituencyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ElectionPosition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElectionVoteMechanism")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VotesReceived")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Candidate", (string)null);
                });

            modelBuilder.Entity("VotifySystem.Common.Models.Constituency", b =>
                {
                    b.Property<string>("ConstituencyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConstituencyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Country")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ElectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConstituencyId");

                    b.ToTable("Constituency", (string)null);
                });

            modelBuilder.Entity("VotifySystem.Common.Models.Elections.Election", b =>
                {
                    b.Property<string>("ElectionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Country")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectionAdministratorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("VoteMechanism")
                        .HasColumnType("INTEGER");

                    b.Property<string>("election_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("ElectionId");

                    b.ToTable("Election", (string)null);

                    b.HasDiscriminator<string>("election_type").HasValue("Election");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VotifySystem.Common.Models.Elections.ElectionVoter", b =>
                {
                    b.Property<string>("ElectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConstituencyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasVoted")
                        .HasColumnType("INTEGER");

                    b.HasKey("ElectionId", "VoterId");

                    b.ToTable("ElectionVoter", (string)null);
                });

            modelBuilder.Entity("VotifySystem.Common.Models.Elections.PreferentialVotePreference", b =>
                {
                    b.Property<string>("PreferenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PreferenceId");

                    b.ToTable("PreferentialVotePreference", (string)null);
                });

            modelBuilder.Entity("VotifySystem.Common.Models.Elections.Vote", b =>
                {
                    b.Property<string>("VoteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElectionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ElectionVoteMechanism")
                        .HasColumnType("INTEGER");

                    b.Property<string>("vote_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("VoteId");

                    b.ToTable("Vote", (string)null);

                    b.HasDiscriminator<string>("vote_type").HasValue("Vote");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("VotifySystem.Common.Models.LoginCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Used")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LoginCode", (string)null);
                });

            modelBuilder.Entity("VotifySystem.Common.Models.Party", b =>
                {
                    b.Property<string>("PartyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Country")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PartyId");

                    b.ToTable("Party", (string)null);
                });

            modelBuilder.Entity("VotifySystem.Common.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("VotifySystem.Common.Models.Elections.FirstPastThePostElection", b =>
                {
                    b.HasBaseType("VotifySystem.Common.Models.Elections.Election");

                    b.HasDiscriminator().HasValue("FPTP_Election");
                });

            modelBuilder.Entity("VotifySystem.Common.Models.Elections.SingleTransferrableVoteElection", b =>
                {
                    b.HasBaseType("VotifySystem.Common.Models.Elections.Election");

                    b.HasDiscriminator().HasValue("STV_Election");
                });

            modelBuilder.Entity("VotifySystem.Common.Models.Elections.FPTPElectionVote", b =>
                {
                    b.HasBaseType("VotifySystem.Common.Models.Elections.Vote");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("FPTP");
                });

            modelBuilder.Entity("VotifySystem.Common.Models.Elections.PreferentialElectionVote", b =>
                {
                    b.HasBaseType("VotifySystem.Common.Models.Elections.Vote");

                    b.HasDiscriminator().HasValue("Preferential");
                });

            modelBuilder.Entity("VotifySystem.Common.Models.Administrator", b =>
                {
                    b.HasBaseType("VotifySystem.Common.Models.User");

                    b.ToTable("Administrator", (string)null);
                });

            modelBuilder.Entity("VotifySystem.Common.Models.Voter", b =>
                {
                    b.HasBaseType("VotifySystem.Common.Models.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Country")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.ToTable("Voter", (string)null);
                });

            modelBuilder.Entity("VotifySystem.Common.Models.Administrator", b =>
                {
                    b.HasOne("VotifySystem.Common.Models.User", null)
                        .WithOne()
                        .HasForeignKey("VotifySystem.Common.Models.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VotifySystem.Common.Models.Voter", b =>
                {
                    b.HasOne("VotifySystem.Common.Models.User", null)
                        .WithOne()
                        .HasForeignKey("VotifySystem.Common.Models.Voter", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
